'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.17929
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自动保存功能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Advanced_Chk_OutPath() As Boolean
            Get
                Return CType(Me("Advanced_Chk_OutPath"),Boolean)
            End Get
            Set
                Me("Advanced_Chk_OutPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Advanced_Chk_Divide() As Boolean
            Get
                Return CType(Me("Advanced_Chk_Divide"),Boolean)
            End Get
            Set
                Me("Advanced_Chk_Divide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Advanced_Chk_OS3_1() As Boolean
            Get
                Return CType(Me("Advanced_Chk_OS3_1"),Boolean)
            End Get
            Set
                Me("Advanced_Chk_OS3_1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Advanced_Chk_EnglishBreakingLine() As Boolean
            Get
                Return CType(Me("Advanced_Chk_EnglishBreakingLine"),Boolean)
            End Get
            Set
                Me("Advanced_Chk_EnglishBreakingLine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Advanced_Txt_Interval() As String
            Get
                Return CType(Me("Advanced_Txt_Interval"),String)
            End Get
            Set
                Me("Advanced_Txt_Interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Advanced_Chk_Image() As Boolean
            Get
                Return CType(Me("Advanced_Chk_Image"),Boolean)
            End Get
            Set
                Me("Advanced_Chk_Image") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Advanced_Chk_NonClip() As Boolean
            Get
                Return CType(Me("Advanced_Chk_NonClip"),Boolean)
            End Get
            Set
                Me("Advanced_Chk_NonClip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Advanced_Chk_ShowCompiler() As Boolean
            Get
                Return CType(Me("Advanced_Chk_ShowCompiler"),Boolean)
            End Get
            Set
                Me("Advanced_Chk_ShowCompiler") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Text_Chk_ChooseColor() As Boolean
            Get
                Return CType(Me("Text_Chk_ChooseColor"),Boolean)
            End Get
            Set
                Me("Text_Chk_ChooseColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property Text_Color_ForeColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("Text_Color_ForeColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Text_Color_ForeColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property Text_Color_BackColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("Text_Color_BackColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Text_Color_BackColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Text_Chk_Size() As Boolean
            Get
                Return CType(Me("Text_Chk_Size"),Boolean)
            End Get
            Set
                Me("Text_Chk_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Text_Txt_Width() As String
            Get
                Return CType(Me("Text_Txt_Width"),String)
            End Get
            Set
                Me("Text_Txt_Width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Text_Txt_Height() As String
            Get
                Return CType(Me("Text_Txt_Height"),String)
            End Get
            Set
                Me("Text_Txt_Height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Text_Chk_ChooseColor_FirstLoad() As Boolean
            Get
                Return CType(Me("Text_Chk_ChooseColor_FirstLoad"),Boolean)
            End Get
            Set
                Me("Text_Chk_ChooseColor_FirstLoad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Form_Chk_ProfessionalMode() As Boolean
            Get
                Return CType(Me("Form_Chk_ProfessionalMode"),Boolean)
            End Get
            Set
                Me("Form_Chk_ProfessionalMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Form_Chk_Batch() As Boolean
            Get
                Return CType(Me("Form_Chk_Batch"),Boolean)
            End Get
            Set
                Me("Form_Chk_Batch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Advanced_Chk_Interval() As Boolean
            Get
                Return CType(Me("Advanced_Chk_Interval"),Boolean)
            End Get
            Set
                Me("Advanced_Chk_Interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("说明："&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"1.仅支持ANSI格式的txt文本文档，如不是请自行转换"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"2.不保证所有大小的文本均能直接在手持设备上直接使用，如提示内存不足请自行分割文本文档"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"3"& _ 
            ".由于Nspire采用16位RGB进行显示，所以背景图片和自定义的配色可能和PC上显示的略有偏差"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"更多说明请参考 《iRead II使用说明》"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"开发代号"& _ 
            ":Faith"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"作者:wtof1996"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"图标:chsi"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"内测人员列表(排名不分先后):"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"imath、ExAcler、月与映之皮丘、chsi、urill、朔"& _ 
            "雪X忆、水瓜、nbzwt、diameter、禾末、老友、虫毛毛、还俗的唐朝和尚、wakaka101、零点五、DAS"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"衷心感谢以上人员能协助测试本程序，并提出了"& _ 
            "很多不错的建议。"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"同时在这里感谢其他一直支持我的人们。"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"欢迎访问中国最大的计算器爱好者专业社区:http:/www.cncalc.org"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"wtof"& _ 
            "1996 ?Copyright 2013 Some rights reserved. 保留部分权利"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"本程序内置了Lua Booster II 的部分核心组件。"& _ 
            ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"本程序内置了Luna V0.31b 作者为Oliver Armand aka ExtendeD。"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"本程序在不同地区适用不同的许可协议。"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"中国大陆(Chi"& _ 
            "nese Mainland)："&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"本程序采用知识共享 署名-相同方式共享 3.0 中国大陆 许可协议进行许可。要查看该许可协议，可访问 http://creat"& _ 
            "ivecommons.org/licenses/by-sa/3.0/cn/ 或者写信到"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Creative Commons, 444 Castro Street"& _ 
            ", Suite 900, Mountain View, California, 94041, USA."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"其他国家/地区(Other countries/reg"& _ 
            "ions):"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"This program is licensed under the Creative Commons Attribution-ShareAli"& _ 
            "ke 3.0 Unported License. To view a copy of this license, visit http://creativeco"& _ 
            "mmons.org/licenses/by-sa/3.0/ or send a letter to Creative Commons, 444 Castro S"& _ 
            "treet, Suite 900, Mountain View, California, 94041, USA.")>  _
        Public ReadOnly Property Abt_Text() As String
            Get
                Return CType(Me("Abt_Text"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.iRead.My.MySettings
            Get
                Return Global.iRead.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
